package my.chairileyarraysassignment;

/**
 *
 * @author Riley Chai
 */
public class ChaiRileyArraysAssignmentUI extends javax.swing.JFrame {
    char[] secret = new char[10];//Declares the secret array globally 
    int numChar = 0;//Declares the number to letters as a global int
    int round = 0;//Declares the round globally
    public ChaiRileyArraysAssignmentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genius Game", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Please enter how many letters you would like to guess (3 - 10): ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Generate Code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("New Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Please enter your guess here (r,g,b):");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setText("Quit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Closes the game
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Generates secret code when the button is pressed 
        numChar = Integer.parseInt(jTextField1.getText());//Parses the user entry to an int
        System.out.println("Secret code:");
        for(int i = 0; i < numChar; i++)
            {
                int random = (int)(Math.random()*3);//Generates a number from 0 - 2            
                switch(random)//Adds the corresponding char to the secret array
                {
                    case 0://Add 'r'
                        secret[i] = 'r';                       
                        break;                    
                    case 1://Add 'g'
                        secret[i] = 'g'; 
                        break;
                    case 2://Add 'b'
                        secret[i] = 'b'; 
                        break;           
               } 
               System.out.println(secret[i]);//Displays secret code generated in the console
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Gets the user guess and checks it with the secret code when the button is pressed
        round++;
        String userGuess = jTextField2.getText();//Stores the user guess from the text field
        int correct = checkGuess(userGuess,secret,numChar);//Sends the guess to a method to check how many letters are correct
        int incorrect = numChar - correct;
        //Prints all of the information in the text area
        String line = "Round "+round+": ";//Concatinate strings onto this main string        
        for(int i = 0; i < numChar; i++)
        {
            line = line+userGuess.charAt(i)+"   |   ";
        }
        line = line+"correct: "+correct+" incorrect: "+incorrect;
        line = line+"\n";//Goes to the next line
        jTextArea1.setText(jTextArea1.getText()+line);
        jTextField2.setText("");
        if(correct == numChar)//If the user guesses all of the letter correctly 
        {
          line = "Congragulations you got it! ";
          line = line+"\n";
          jTextArea1.setText(jTextArea1.getText()+line); 
          jTextField2.setText(""); 
          line = "A new code has been generated with the same length. Please guess "+numChar+" letters";
          line = line+"\n";
          jTextArea1.setText(jTextArea1.getText()+line);
          //Generate a new code without user input
          round = 0;
          System.out.println("New Code:");
          for(int i = 0; i < numChar; i++)
            {
                int random = (int)(Math.random()*3);//Generates a number from 0 - 2            
                switch(random)//Adds the corresponding char to the secret array
                {
                    case 0://Add 'r'
                        secret[i] = 'r';                       
                        break;                    
                    case 1://Add 'g'
                        secret[i] = 'g'; 
                        break;
                    case 2://Add 'b'
                        secret[i] = 'b'; 
                        break;           
               } 
               System.out.println(secret[i]);//Displays secret code generated in the console
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Starts a new game. Resets everything.
        jTextField1.setText(""); 
        jTextField2.setText(""); 
        jTextArea1.setText("");
        numChar = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        //Same as button, Generate secret code when enter is pressed
        numChar = Integer.parseInt(jTextField1.getText());//Parses the user entry to an int
        System.out.println("Secret code:");
        for(int i = 0; i < numChar; i++)
            {
                int random = (int)(Math.random()*3);//Generates a number from 0 - 2            
                switch(random)//Adds the corresponding char to the secret array
                {
                    case 0://Add 'r'
                        secret[i] = 'r';                       
                        break;                    
                    case 1://Add 'g'
                        secret[i] = 'g'; 
                        break;
                    case 2://Add 'b'
                        secret[i] = 'b'; 
                        break;           
               } 
               System.out.println(secret[i]);//Displays secret code generated in the console
            }    
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        //Gets the user guess and checks it with the secret code when enter is pressed
        round++;
        String userGuess = jTextField2.getText();//Stores the user guess from the text field
        int correct = checkGuess(userGuess,secret,numChar);//Sends the guess to a method to check how many letters are correct
        int incorrect = numChar - correct;
        //Prints all of the information in the text area
        String line = "Round "+round+": ";//Concatinate strings onto this main string        
        for(int i = 0; i < numChar; i++)
        {
            line = line+userGuess.charAt(i)+"   |   ";
        }
        line = line+"correct: "+correct+" incorrect: "+incorrect;
        line = line+"\n";//Goes to the next line
        jTextArea1.setText(jTextArea1.getText()+line);
        jTextField2.setText("");
        if(correct == numChar)//If the user guesses all of the letter correctly 
        {
          line = "Congragulations you got it! ";
          line = line+"\n";
          jTextArea1.setText(jTextArea1.getText()+line); 
          jTextField2.setText(""); 
          line = "A new code has been generated with the same length. Please guess "+numChar+" letters";
          line = line+"\n";
          jTextArea1.setText(jTextArea1.getText()+line);
          //Generate a new code without user input
          round = 0;
          System.out.println("New Code:");
          for(int i = 0; i < numChar; i++)
            {
                int random = (int)(Math.random()*3);//Generates a number from 0 - 2            
                switch(random)//Adds the corresponding char to the secret array
                {
                    case 0://Add 'r'
                        secret[i] = 'r';                       
                        break;                    
                    case 1://Add 'g'
                        secret[i] = 'g'; 
                        break;
                    case 2://Add 'b'
                        secret[i] = 'b'; 
                        break;           
               } 
               System.out.println(secret[i]);//Displays secret code generated in the console
            }
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaiRileyArraysAssignmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaiRileyArraysAssignmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaiRileyArraysAssignmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaiRileyArraysAssignmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChaiRileyArraysAssignmentUI().setVisible(true);
            }
        });
    }
    public static int checkGuess(String userGuess, char[] secret, int numChar){//Checks the guess array with the secret array
        int numCorrect = 0;//Declares a variable to store how many letters are correct
        char[] guess = new char[numChar];//Sets the guess array to the user length
        for(int i = 0; i < numChar; i++){//stores the user guess in the guess array
                    guess[i] = userGuess.charAt(i);
                }               
                //Compare guess to secret code
                for(int q = 0; q < numChar; q++)
                {
                    if(secret[q] == guess[q])//If a letter matches, add one to numCorrect
                    {
                        numCorrect++;      
                    }
                }      
            return numCorrect;//Returns how many letter are correct
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
